# Generated by Django 3.0 on 2019-12-14 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robots', '0003_auto_20191212_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='url',
            name='pattern',
            field=models.CharField(help_text="Case-sensitive. A missing trailing slash does also match to files which start with the name of the pattern, e.g., '/admin' matches /admin.html too. Some major search engines allow an asterisk (*) as a wildcard and a dollar sign ($) to match the end of the URL, e.g., '/*.jpg$'.", max_length=255, unique=True, verbose_name='pattern'),
        ),
    ]
